-- Instrument metadata for every ticker currently appearing in transactions.

INSERT INTO instruments (ticker, name, category, market_ticker) VALUES
    ('ANANTRAJ',   'Anant Raj Ltd',               'stock', 'ANANTRAJ.NS'),
    ('ASHOKLEY',   'Ashok Leyland',               'stock', 'ASHOKLEY.NS'),
    ('BSE',        'BSE Ltd',                     'stock', 'BSE.NS'),
    ('CANBK',      'Canara Bank',                 'stock', 'CANBK.NS'),
    ('ECOSMOBLTY', 'Eco Smart Mobility Ltd',      'stock', 'ECOSMOBLTY.NS'),
    ('EIEL',       'Enviro Infra Engineers Ltd',  'stock', 'EIEL.NS'),
    ('ETERNAL',    'Eternal',                     'stock', 'ETERNAL.NS'),
    ('FISCHER',    'Fischer Medical Ventures',    'stock', 'FISCHER.NS'),
    ('GOLDBEES',   'Nippon India GoldBees',       'etf',   'GOLDBEES.NS'),
    ('HNGSNGBEES', 'Hang Seng BeES',              'etf',   'HNGSNGBEES.NS'),
    ('HDFCBANK',   'HDFC Bank',                   'stock', 'HDFCBANK.NS'),
    ('HAPPSTMNDS', 'Happiest Minds Technology',   'stock', 'HAPPSTMNDS.NS'),
    ('IRCTC',      'IRCTC',                       'stock', 'IRCTC.NS'),
    ('IT',         'Kotak Nifty IT ETF',          'etf',   'IT.NS'),
    ('ITC',        'ITC',                         'stock', 'ITC.NS'),
    ('ITCHOTELS',  'ITC Hotels',                  'stock', 'ITCHOTELS.NS'),
    ('KPIT',       'KPIT Technologies',           'stock', 'KPIT.NS'),
    ('LICI',       'LIC India',                   'stock', 'LICI.NS'),
    ('MON100',     'Motilal Oswal Nasdaq 100 ETF','etf',   'MON100.NS'),
    ('MOSMALL250', 'Motilal Oswal Small 250 ETF', 'etf',   'MOSMALL250.NS'),
    ('MIDCAPIETF', 'ICICI Midcap 150 ETF',        'etf',   'MIDCAPIETF.NS'),
    ('NIFTYIETF',  'ICICI Nifty 50 ETF',          'etf',   'NIFTYIETF.NS'),
    ('NEXT50IETF', 'ICICI Nifty Next 50 ETF',     'etf',   'NEXT50IETF.NS'),
    ('NSE',        'NSE Ltd',                     'stock', 'NSE.BO'),
    ('NTPC',       'NTPC',                        'stock', 'NTPC.NS'),
    ('PFC',        'PFC',                         'stock', 'PFC.NS'),
    ('POWERGRID',  'Power Grid Corporation',      'stock', 'POWERGRID.NS'),
    ('RECLTD',     'REC Ltd',                     'stock', 'RECLTD.NS'),
    ('RELIANCE',   'Reliance Industries',         'stock', 'RELIANCE.NS'),
    ('SILVERIETF', 'ICICI Silver ETF',            'etf',   'SILVERIETF.NS'),
    ('TATAPOWER',  'Tata Power',                  'stock', 'TATAPOWER.NS'),
    ('TMPV',       'Tata Motors Passenger Vehicles','stock', 'TMPV.NS'),
    ('VIKRAMSOLR', 'Vikram Solar',                'stock', 'VIKRAMSOLR.NS'),
    ('WONDERLA',   'Wonderla Holidays',           'stock', 'WONDERLA.NS');